services:
  - type: web
    name: policybridge-backend
    env: python
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn policybridge_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: GEMINI_API_KEY
        sync: false # User must provide this in the Render dashboard
    autoDeploy: false
