# Generated by Django 5.2.4 on 2025-08-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='conversation_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Conversation Count'),
        ),
    ]
